export const GET_STATIONS_REQUEST = 'GET_STATIONS_REQUEST';
export const GET_STATIONS_SUCCESS = 'GET_STATIONS_SUCCESS';
export const GET_STATIONS_FAILURE = 'GET_STATIONS_FAILURE';
export const SHOW_STATION_DETAILS = 'SHOW_STATION_DETAILS';
