export const GET_STATIONS_REQUEST = 'GET_STATIONS_REQUEST';
export const GET_STATIONS_SUCCESS = 'GET_STATIONS_SUCCESS';
export const GET_STATIONS_FAILURE = 'GET_STATIONS_FAILURE';
export const SHOW_STATION_DETAILS = 'SHOW_STATION_DETAILS';

export const GET_CHALLENGES_REQUEST = 'GET_CHALLENGES_REQUEST';
export const GET_CHALLENGES_SUCCESS = 'GET_CHALLENGES_SUCCESS';
export const GET_CHALLENGES_FAILURE = 'GET_CHALLENGES_FAILURE';
export const SHOW_CHALLENGE_DETAILS = 'SHOW_CHALLENGE_DETAILS';
export const SELECT_CHALLENGE = 'SELECT_CHALLENGE';

